# Generated by Django 3.2.8 on 2021-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='photos')),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
    ]
